name: Strip logger.trace statements

# When should this workflow run?
on:
  push:
    branches:
      - '**'

jobs:
  strip-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run sed replacement
        run: |
          find . -type f -name "*.py" -exec sed -i '/logger\.trace/d' {} +
