name: CI

# When should this workflow run?
on:
  push:
    branches:
      - '**'

  # pull_request:
  #   branches:
      # - main
      # - develop


jobs:
  strip-logs:
    # --------------------------------------------------
    # 0. Strip logger.trace statements
    # --------------------------------------------------
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run sed replacement
        run: |
          find . -type f -name "*.py" -exec sed -i '/logger\.trace/d' {} +

  video-test:
    name: Run Robotics Subsystem Video Test

    # GitHub's temporary Ubuntu machine
    runs-on: ubuntu-latest

    env:
      QT_QPA_PLATFORM: offscreen

    steps:
      # --------------------------------------------------
      # 1. Download your repository
      # --------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 2. Set up uv
      # --------------------------------------------------
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"

      # --------------------------------------------------
      # 4. Verify Git LFS files actually exist
      # --------------------------------------------------
      # - name: Verify Git LFS files
      #   run: |
      #     git lfs ls-files
      #     git lfs pull

      # --------------------------------------------------
      # 6. Run your actual robotics subsystem
      # --------------------------------------------------
      - name: Run Huey vs Prince
        env:
          TEST_VIDEO: "test_videos/shorty_vs_prince.mp4"
          MATRIX: "/homography_matrix_test.txt"
          COLOR: "/selected_colors_test.txt"
        run: |
          uv run --with-requirements requirements-ci.txt python test.py
      - name: Run 2-Corners
        env: 
          TEST_VIDEO: "test_videos/blink224_huey.mp4"
          MATRIX: "/homography_matrix_2corn.txt"
          COLOR: "/selected_colors_2corn.txt"
        run: |
          uv run --with-requirements requirements-ci.txt python test.py